#! /bin/sh

function env_set() {
	[ -n "$DS_HOME" ]
}

function get_vms_dir() {
	env_set && echo "$DS_HOME"/vms || echo "$HOME"/vms
}

function get_ram_dir() {
	env_set && echo "$DS_HOME"/ram || echo "$HOME"/vms/ram
}

vms_dir=$(get_vms_dir)
ram_dir=$(get_ram_dir)

[ -z "$vms_dir" ] || [ -z "$ram_dir" ] && {
	printf "\033[31mERROR: Empty parameter found:\n\tvms_dir: '%s'\n\tram_dir: '%s'\n\033[0m" \
		"$vms_dir" \
		"$ram_dir"
	exit 1
}

function sync_containers() {
	local vms_dir="$1"
	local ram_dir="$2"

	for dir in $(ls "$ram_dir");
	do
		local target_dir="$vms_dir"/"$dir"
		[ ! -d "$target_dir" ] && continue

		printf "\033[32mSynchronizing '%s'...\n\033[0m" "$target_dir"

		sudo rsync -a -q --recursive --links --delete -P "$ram_dir"/"$dir"/ "$target_dir" &&
			printf "\033[32m'%s' synchronized.\n\033[0m" "$target_dir"
	done
}

[ -d "$vms_dir" ] && [ -d "$ram_dir" ] && sync_containers "$vms_dir" "$ram_dir"


