#! /bin/sh

container="$1"
vms_dir="$2"
ram_dir="$3"

[ -z "$container" ] || [ -z "$vms_dir" ] || [ -z "$ram_dir" ] && {
	printf "\033[31mERROR: Empty parameter found:\n\tcontainer: '%s'\n\tvms_dir: '%s'\n\tram_dir: '%s'\n\033[0m" \
		"$container" \
		"$vms_dir" \
		"$ram_dir"
	exit 1
}

target_container_location="$ram_dir"/"$container"
[ -d "$target_container_location" ] && {
	printf "\033[33m[WARNING] The '%s' container has been brought up previously. It will not be reloaded from the disk.\n" "$container"
        printf "\033[31m[DANGER] \033[0m\033[33mIf you need to reload it remove '%s' directory and start the container again:\n\033[0m" "$target_container_location"
	printf "\n\trm -rf '%s'\n\n" "$target_container_location"
	exit 0
}

container_dir="$vms_dir"/"$container"

[ ! -d "$container_dir" ] && {
	printf "\033[31mERROR: No container's directory '$container_dir' found. \033[0m" >&2
	printf "\033[31mPlease create the '$container' container\n\033[0m" >&2
	exit 1
}

[ ! -d "$ram_dir" ] && {
	echo No "$ram_dir" RAM directory exists >&2
	exit 1
}

printf "\033[32mBringing up '%s' at '%s'...\n\033[0m" "$container" "$target_container_location"

rsync -a -q --links --recursive --delete -P "$container_dir" "$ram_dir" &&
	printf "\033[32mThe '%s' container is available at '%s'.\n\033[0m" "$container" "$target_container_location"
