#! /bin/sh

ROOT_DIR="$(dirname "$0")"

source "$ROOT_DIR"/util.sh || exit 1

container="$1"
img_dir="$2"
ram_dir="$3"
perform_common_checks="${4:-y}"

target_container_location="$ram_dir"/"$container"

container_dir="$img_dir"/"$container"

function perform_checks() {
	[ "$perform_common_checks" == "y" ] && {
		common_prechecks "$container" "$img_dir" "$ram_dir" || return 1
	}

	[ -d "$container_dir" ] || {
		error 'The "%s" directory of the "%s" container does not exists. Please create the "%s" container.'\
			"$container_dir" \
			"$container" \
			"$container"
		return 1
	}
}

function container_already_active() {
	local target_container_location="$1"

	[ -d "$target_container_location" ] && {
		warn 'The "%s" container has been brought up previously. It will not be reloaded from the disk.' "$container"
		warn 'If you need to reload it remove the "%s" directory and start the container again:\n\tsudo rm -rf "%s"\n\n' \
			"$target_container_location" \
			"$target_container_location"
	}
}

function copy_to_ram() {
	local container="$1"
	local target_container_location="$2"

	info 'Bringing up "%s" at "%s"...' "$container" "$target_container_location"

	rsync -a -q --links --recursive --delete -P "$container_dir" "$ram_dir" &&
		success 'The "%s" container is available at "%s".\n' "$container" "$target_container_location"
}

container_already_active "$target_container_location" || {
	perform_checks &&
	copy_to_ram "$container" "$target_container_location"
}
