#! /usr/bin/env bash

ROOT_DIR="$(dirname "$0")"
source "$ROOT_DIR"/util.sh || exit 1

command="$1"

function start_container() {
	"$ROOT_DIR"/container-start "$@"
}

case "$command" in
	"start")
		shift
		start_container "$@"
		;;
	*)
		error 'unknown command "%s"' "$command"
		;;
esac
