#! /usr/bin/env bash

ROOT_DIR="$(dirname "$0")"
source "$ROOT_DIR"/util.sh || exit 1

command=${1:-local}

function list_local() {
	list_local_containers
}

function list_remote() {
	local filter="$1"
	list_remote_containers | grep "$filter" -i
}

function list_active() {
	local filter="${1:-*}"

	local ram_dir=$(get_ram_dir)

	for container_dir in $(find "$ram_dir" -maxdepth 1 -type d -name "*$filter*");
	do
		[ "$container_dir" == "$ram_dir" ] && continue

		echo "$(basename "$container_dir")"
	done
}

case "$command" in
	"local")
		list_local
		;;
	"remote")
		shift
		list_remote "$@"
		;;
	"active")
		shift
		list_active "$@"
		;;
	*)
		error '"%s" is unable to handle "%s"' "$0" "$command"
		;;
esac
