#! /usr/bin/env bash

ROOT_DIR="$(dirname "$0")"
source "$ROOT_DIR"/util.sh || exit 1

function list_local() {
	local filter="$1"
	list_local_containers | grep -i -e "$filter"
}

function list_remote() {
	local filter="$1"
	list_remote_containers | grep -i -e "$filter"
}

function list_booted() {
	local filter="${1:-*}"

	local ram_dir=$(get_ram_dir)

	for container_dir in $(find "$ram_dir" -maxdepth 1 -type d -name "*$filter*");
	do
		[ "$container_dir" == "$ram_dir" ] && continue

		echo "$(basename "$container_dir")"
	done
}

function list_containers() {
	local option="${1:---local}"
	local fitler="$2"

	case "$option" in
		"-l"|"--local")
			list_local "$filter"
			;;
		"-r"|"--remote")
			list_remote "$filter"
			;;
		"-b"|"--booted")
			list_booted "$filter"
			;;
	esac
}

function parse_args() {
	while : ; do
		local value="$1"

		case "$value" in
			"-l"|"--local")
				[ -z "$option" ] &&
					option="$value" ||
					error "please specify only one of '-l', '-r', '-b'"
				;;
			"-r"|"--remote")
				[ -z "$option" ] &&
					option="$value" ||
					error "please specify only one of '-l', '-r', '-b'"
				;;
			"-b"|"--booted")
				[ -z "$option" ] &&
					option="$value" ||
					error "please specify only one of '-l', '-r', '-b'"
				;;
			*)
				[ -z "$filter" ] &&
					filter="$value" ||
					error "Unable to handle multiple filters"
				;;
		esac

		local valid="$?"
		[ "$valid" -ne "0" ] && return 1

		shift && [ -n "$1" ] || break
	done
}

name=$(basename "$0")

case "$1" in
	"-h"|"--help")
		echo 'Name: ' "$name"
		echo 'Description: show the list of local, booted and remote containers'
		printf 'usage: %s -a | -b | -r' "$name"
		exit 0
		;;
esac


parse_args "$@" && list_containers "$option" "$filter"
