#! /bin/sh

ROOT_DIR="$(dirname "$0")"
source "$ROOT_DIR"/util.sh || exit 1

function file_exists() {
	local path="$1"
	[ -d "$path" ] || {
		warn '"%s" does not exists' "$path"
	}
}

function remove_confirmed() {
	local path="$1"

	read -p "Removing $path?[Y/n] " confirm
	local confirm=${confirm:-Y}

	[ "${confirm^^}" == "Y" ]
}

function remove_file() {
	local path="$1"

	(
		errors=$(mktemp)
		trap "rm $errors" EXIT
		local output=$(sudo rm "$path" -r 2>"$errors" && echo '"'"$path"'"' removed)
		[ -n "$output" ] && success "$output" || error "$(cat "$errors")"
	)
}

function remove() {
	local base_dir="$1"

	shift

	for container in "$@"
	do
		local path="$base_dir"/"$container"

		file_exists "$path" &&
			remove_confirmed "$path" &&
			remove_file "$path"
	done
}

function remove_active() {
	local base_dir=$(get_ram_dir)
	remove "$base_dir" "$@"
}

function remove_image() {
	local base_dir="$(get_img_dir)"
	remove "$base_dir" "$@"
}

option="$1"

case "$option" in
	"-i"|"--active")
		shift
		remove_active "$@"
		;;
	*)
		remove_image "$@"
		;;
esac

# ensure_dirs "$img_dir" "$ram_dir" &&
